export const ACTION_POPULAR_MOVIE_REQUEST = 'ACTION_POPULAR_MOVIE_REQUEST';
export const ACTION_POPULAR_MOVIE_RESPONSE = 'ACTION_POPULAR_MOVIE_RESPONSE';
export const ACTION_POPULAR_MOVIE_ERROR = 'ACTION_POPULAR_MOVIE_ERROR';

export function popularMovieData() {
  return {
    type: ACTION_POPULAR_MOVIE_REQUEST,
  };
}
